In [1]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime

from pymongo import MongoClient

from bson.objectid import ObjectId

## Intial run

In [2]:
# Intial run
def readdata():
    with MongoClient('mongodb://collectionreader:Lacritz12345%23@85.214.144.66:27017/?authSource=dclmdb&readPreference=primary&appname=MongoDB%20Compass&ssl=false') as client:
        filter={}

        result = client['testdb']['A01000_collection'].find(
          filter=filter
        )

    df = pd.DataFrame()

    for i in result:
        df = df.append(i, ignore_index=True)
    
    return df

In [3]:
df = readdata()

# df_envelope = pd.DataFrame(index=df.index, columns=['_id','sessionId', 'userId', 'projectId', 'duration',
#        'start', 'end', 'version', 'sequence', 'pageNum', 'upload', 'DateTime','pointer', 'click'])


# for label, content in df.iterrows():
#     col = content.envelope.keys()
#     for c in col:
#         df_envelope.loc[label,c] = content.envelope[c]
    
#     df_envelope.loc[label,'DateTime'] = datetime.fromtimestamp(content.timestamp/1000)
    
#     df_envelope.loc[label,'pointer'] = content.pointer
    
#     df_envelope.loc[label,'click'] = content.click
    
#     df_envelope.loc[label,'_id'] = content._id

# Navigation

In [50]:
#  first time only
df_nv = pd.DataFrame(columns=['_id','nv_time','nv_event','nv_data_fetchstart','nv_data_connectStart',
                                      'nv_data_connectEnd','nv_data_requestStart','nv_data_responseStart',
                                     'nv_data_responseEnd','nv_data_domInteractive','nv_data_domComplete',
                                     'nv_data_loadEventStart','nv_data_loadEventEnd','nv_data_redirectCount',
                                     'nv_data_size','nv_data_type','nv_data_protocol','nv_data_encodedSize',
                                      'nv_data_decodedSize'])

In [13]:
df_nv

Empty DataFrame
Columns: [_id, nv_time, nv_event, nv_data_fetchstart, nv_data_connectStart, nv_data_connectEnd, nv_data_requestStart, nv_data_responseStart, nv_data_responseEnd, nv_data_domInteractive, nv_data_domComplete, nv_data_loadEventStart, nv_data_loadEventEnd, nv_data_redirectCount, nv_data_size, nv_data_type, nv_data_protocol, nv_data_encodedSize, nv_data_decodedSize]
Index: []

In [8]:
# df_pointer = pd.read_csv('D:\DataWorld\lacritz\data\clarity\pointer_data.csv',index_col=0 )

df.navigation[0]

[{'time': 240,
  'event': 29,
  'data': {'fetchStart': 1,
   'connectStart': 1,
   'connectEnd': 1,
   'requestStart': 9,
   'responseStart': 1184,
   'responseEnd': 1202,
   'domInteractive': 1412,
   'domComplete': 2397,
   'loadEventStart': 2397,
   'loadEventEnd': 2398,
   'redirectCount': 0,
   'size': 92682,
   'type': 'reload',
   'protocol': 'http/1.1',
   'encodedSize': 92370,
   'decodedSize': 92370}}]

In [59]:
df.iloc[:101].navigation[0]

[{'time': 240,
  'event': 29,
  'data': {'fetchStart': 1,
   'connectStart': 1,
   'connectEnd': 1,
   'requestStart': 9,
   'responseStart': 1184,
   'responseEnd': 1202,
   'domInteractive': 1412,
   'domComplete': 2397,
   'loadEventStart': 2397,
   'loadEventEnd': 2398,
   'redirectCount': 0,
   'size': 92682,
   'type': 'reload',
   'protocol': 'http/1.1',
   'encodedSize': 92370,
   'decodedSize': 92370}}]

In [60]:
# This will find out the recent updated rows into the database and update df_pointer table for new data.( it will save unnecessary processing)

#df_pointer = pd.read_csv('D:\DataWorld\lacritz\data\clarity\pointer_data.csv',index_col=0 )

#df_new_pointers = df[df.timestamp>df[df._id==ObjectId(df_pointer['_id'].iloc[-1])].timestamp.values[0]]

for index, content in df.iterrows():
    if isinstance(content.navigation,list):
        for nv_ in content.navigation:
           
            d = {'_id':content['_id'],'nv_time':nv_.get('time'),'nv_event':nv_.get('event'),
                 'nv_data_fetchstart':nv_.get('data').get('fetchStart'),
                 'nv_data_connectStart':nv_.get('data').get('connectStart'),
                 'nv_data_connectEnd':nv_.get('data').get('connectEnd'),
                 'nv_data_requestStart':nv_.get('data').get('requestStart'),
                 'nv_data_responseStart':nv_.get('data').get('responseStart'),
                 'nv_data_responseEnd':nv_.get('data').get('responseEnd'),
                 'nv_data_domInteractive':nv_.get('data').get('domInteractive'),
                 'nv_data_domComplete':nv_.get('data').get('domComplete'),
                 'nv_data_loadEventStart':nv_.get('data').get('loadEventStart'),
                 'nv_data_loadEventEnd':nv_.get('data').get('loadEventEnd'),
                 'nv_data_redirectCount':nv_.get('data').get('redirectCount'),
                 'nv_data_size':nv_.get('data').get('size'),
                 'nv_data_type':nv_.get('data').get('type'),
                 'nv_data_protocol':nv_.get('data').get('protocol'),
                 'nv_data_encodedSize':nv_.get('data').get('encodedSize'),
                 'nv_data_decodedSize':nv_.get('data').get('decodedSize')
             } 
            df_nv = df_nv.append(d, ignore_index=True)
    else:
        {'_id':content['_id'],'nv_time':'nan',
                 'nv_data_fetchstart':'nan',
                 'nv_data_connectStart':'nan',
                 'nv_data_connectEnd':'nan',
                 'nv_data_requestStart':'nan',
                 'nv_data_responseStart':'nan',
                 'nv_data_responseEnd':'nan',
                 'nv_data_domInteractive':'nan',
                 'nv_data_domComplete':'nan',
                 'nv_data_loadEventStart':'nan',
                 'nv_data_loadEventEnd':'nan',
                 'nv_data_redirectCount':'nan',
                 'nv_data_size':'nan',
                 'nv_data_type':'nan',
                 'nv_data_protocol':'nan',
                 'nv_data_encodedSize':'nan',
                 'nv_data_decodedSize':'nan'
             } 
        df_nv = df_nv.append(d, ignore_index=True)
            

# t = datetime.datetime.now()
# timestamp = str(t.year)+'_'+str(t.month)+'_'+str(t.day)+'_'+str(t.hour)+'_'+str(t.minute)+'_'+str(t.second)
            

df_nv.to_csv("D:\DataWorld\lacritz\data\clarity\\nv_data.csv")
# df_pointer.to_csv('D:\DataWorld\lacritz\data\clarity\backup\pointer_data_'+timestamp+'.csv')

In [63]:
df_nv

,_id,nv_time,nv_event,nv_data_fetchstart,nv_data_connectStart,nv_data_connectEnd,nv_data_requestStart,nv_data_responseStart,nv_data_responseEnd,nv_data_domInteractive,nv_data_domComplete,nv_data_loadEventStart,nv_data_loadEventEnd,nv_data_redirectCount,nv_data_size,nv_data_type,nv_data_protocol,nv_data_encodedSize,nv_data_decodedSize
0,605b26139ddab75267083666,240,29,1,1,1,9,1184,1202,1412,2397,2397,2398,0,92682,reload,http/1.1,92370,92370
1,605f3a829055ec40687183cb,240,29,1,1,1,9,1184,1202,1412,2397,2397,2398,0,92682,reload,http/1.1,92370,92370
2,605f558e0c9ec818d902a8a8,240,29,1,1,1,9,1184,1202,1412,2397,2397,2398,0,92682,reload,http/1.1,92370,92370
3,605f7322a0423e1ec4b8c618,189,29,2,2,2,0,3,3,60,60,60,60,0,103787,navigate,,103312,103312
4,605f7322a0423e1ec4b8c618,189,29,2,2,2,0,3,3,60,60,60,60,0,103787,navigate,,103312,103312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,606f197818741e3e8e161829,832,29,1241,1241,1241,1247,1490,1494,1653,2554,2554,2554,1,19220,navigate,h3-Q050,18980,69924
669,606f197818741e3e8e161829,832,29,1241,1241,1241,1247,1490,1494,1653,2554,2554,2554,1,19220,navigate,h3-Q050,18980,69924
670,606f197818741e3e8e161829,832,29,1241,1241,1241,1247,1490,1494,1653,2554,2554,2554,1,19220,navigate,h3-Q050,18980,69924
671,606f197818741e3e8e161829,832,29,1241,1241,1241,1247,1490,1494,1653,2554,2554,2554,1,19220,navigate,h3-Q050,18980,69924
672,606f197818741e3e8e161829,832,29,1241,1241,1241,1247,1490,1494,1653,2554,2554,2554,1,19220,navigate,h3-Q050,18980,69924

# Click

In [64]:
#  first time only
df_click = pd.DataFrame(columns=['_id','click_time','click_event','click_data_target','click_data_x','click_data_y',
                                 'click_data_eX','click_data_eY','click_button','click_reaction','click_context',
                                 'click_text','click_link','click_hash','click_region'])

df_click.to_csv('D:\DataWorld\lacritz\data\clarity\click_data.csv')

In [189]:
df_click.shape

(0, 15)

In [186]:
df.click.loc[646]

[{'time': 1736,
  'event': 9,
  'data': {'target': 346,
   'x': 1096,
   'y': 46,
   'eX': 13106,
   'eY': 16034,
   'button': 0,
   'reaction': 1,
   'context': 0,
   'text': 'About',
   'link': 'https://mytravelexp.com/about/',
   'hash': '57c7ho921',
   'region': None}}]

In [65]:
# This will find out the recent updated rows into the database and update df_pointer table for new data.( it will save unnecessary processing)


# df_new_click = df[df.timestamp>=df[df._id==df_click['_id'].iloc[-1]].timestamp.values[0]]

for index, content in df.iterrows():
    if isinstance(content.click,list):
        for click_ in content.click:
           
            d = {'_id':content['_id'], 'click_time':click_.get('time'),'click_event':click_.get('event'),
                 'click_data_target':click_.get('data').get('target'),'click_data_x':click_.get('data').get('x'),
                 'click_data_y':click_.get('data').get('y'),'click_data_eX':click_.get('data').get('eX'),
                 'click_data_eY':click_.get('data').get('eY'),'click_data_button':click_.get('data').get('button'),
                 'click_data_reaction':click_.get('data').get('reaction'),
                 'click_data_context':click_.get('data').get('context'),
                 'click_data_text':click_.get('data').get('text'),'click_data_link':click_.get('data').get('link'),
                 'click_data_hash':click_.get('data').get('hash'),'click_data_region':click_.get('data').get('region')}

            df_click = df_click.append(d, ignore_index=True)
    else:
         d = {'_id':content['_id'], 'click_time':'nan','click_event':'nan',
                 'click_data_target':'nan','click_data_x':'nan',
                 'click_data_y':'nan','click_data_eX':'nan',
                 'click_data_eY':'nan','click_data_button':'nan',
                 'click_data_reaction':'nan',
                 'click_data_context':'nan',
                 'click_data_text':'nan','click_data_link':'nan',
                 'click_data_hash':'nan','click_data_region':'nan'}
         df_click = df_click.append(d, ignore_index=True)

In [66]:
df_click.tail(10)

,_id,click_time,click_event,click_data_target,click_data_x,click_data_y,click_data_eX,click_data_eY,click_button,click_reaction,...,click_link,click_hash,click_region,click_data_button,click_data_context,click_data_hash,click_data_link,click_data_reaction,click_data_region,click_data_text
697,606f196d18741e3e8e161825,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
698,606f197118741e3e8e161826,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
699,606f197118741e3e8e161827,3050,9,300,827,48,12638,16732,NaN,NaN,...,NaN,NaN,NaN,0,0,7jhgladrd,https://mytravelexp.com/,1,None,Home
700,606f197418741e3e8e161828,1602,9,867,748,602,14790,6241,NaN,NaN,...,NaN,NaN,NaN,0,0,2qt306ak5,https://mytravelexp.com/about,1,None,Learn More
701,606f197818741e3e8e161829,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
702,606f19b518741e3e8e16182a,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
703,606f19f218741e3e8e16182b,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
704,606f1a2f18741e3e8e16182c,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
705,606f1a6c18741e3e8e16182d,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan
706,606f1aa918741e3e8e16182e,nan,nan,nan,nan,nan,nan,nan,NaN,NaN,...,NaN,NaN,NaN,nan,nan,nan,nan,nan,nan,nan